### ISSUE TITLE
Add support for running periodic tasks

### ISSUE THREAD

**Issue by anandology** [rorodata/rorolite#4]
Implement the ability to specify tasks in the `rorolite.yml` file and translate that into a cron file on every deploy.

**Comment by manuhg** [comment]
@anandology What is the format of cron specification?  I mean will it be in the standard cron syntax or natual language?

**Comment by anandology** [comment]
It'll be specified in a natural language in `rorolite.yml`. For example:

```
tasks:
    - name: retrain
      command: python train.py
      when: "everyday at 10:00 AM"
```

The `rorolite deploy` command should translate that into appropriate crontab file.
